package com.gobaskt.offers.model;

import java.util.List;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBScalarAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "basket_Activity")
public class BasketActivity {
	@Id
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey
	private String id;
	@DynamoDBAttribute
	private String basket_userId;
	@DynamoDBAttribute
	private OffersAdded offers;

}
