package com.gobaskt.offers.model;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName="BrandOfferDummy")
public class BrandOfferDummy {
	@Id
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey
	private String id;
	@DynamoDBAttribute
	private String Userid;
	@DynamoDBAttribute
	private String InternalCouponID;
	@DynamoDBAttribute
	private String offerTitle;
	@DynamoDBAttribute
	private String offerValue;
	@DynamoDBAttribute
	private String offerTerms;
	@DynamoDBAttribute
	private String products;
	@DynamoDBAttribute
	private String offerDescription;
	@DynamoDBAttribute
	private String BrandName;
	@DynamoDBAttribute
	private String offerSubCategory;
	@DynamoDBAttribute
	private String offerCategory;
	@DynamoDBAttribute
	private String offerSuperCategory;
	@DynamoDBAttribute
	private String clipped;
	@DynamoDBAttribute
	private String dateClipped;
	@DynamoDBAttribute
	private String viewedDescription;
	@DynamoDBAttribute
	private String viewIntensity;
	@DynamoDBAttribute
	private String dateViewed;
	@DynamoDBAttribute
	private String Redeemed;
	@DynamoDBAttribute
	private String dateRedeemed;
	@DynamoDBAttribute
	private String YrForFreq;
	@DynamoDBAttribute
	private String clippingFrequency;
	@DynamoDBAttribute
	private String redemptionFrequency;
	@DynamoDBAttribute
	private String couponAffinityScore;
	@DynamoDBAttribute
	private String UPCCode;
	@DynamoDBAttribute
	private String offerExpirydate;
	@DynamoDBAttribute
	private String EANCode;
	@DynamoDBAttribute
	private String WebOfferImage1;
	@DynamoDBAttribute
	private String WebOfferImage2;
	@DynamoDBAttribute
	private String MobileOfferImage1;
	@DynamoDBAttribute
	private String MobileOfferImage2;
	@DynamoDBAttribute
	private String top_value_coupon_For_that_category_same_day;
	@DynamoDBAttribute
	private String Top_coupon_for_that_brand_at_the_time_of_clipping;
	@DynamoDBAttribute
	private String Top_coupon_for_that_category_at_the_time_of_clipping;
	@DynamoDBAttribute
	private String Top_coupon_for_that_brand_at_the_time_of_redeeming;
	@DynamoDBAttribute
	private String Top_coupon_for_that_category_at_the_time_of_redeeming;
	@DynamoDBAttribute
	private String searchData;
}
