AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Simple implementation of a REST API for an imaginary todo app.
Globals:
  Function:
    Runtime: java8
    Timeout: 60
    MemorySize: 256
  Api:
    Cors: '''*'''
Parameters:
  StageName:
    Type: String
    Default: dev
    Description: The Lambda Function Stage
Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: gobaskt-offers-${StageName}
      StageName:
        Ref: StageName
  ListLocaloffersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: gobaskt-lists-localoffers-${StageName}
      CodeUri: target/test-0.0.1-SNAPSHOT.jar
      Handler: com.gobaskt.offers.handlers.TaskRequestHandler::listTasks
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: TasksTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /gobaskt/offers
            Method: GET
            RestApiId:
              Ref: RestApi
  ListLocaloffersPublishedFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: gobaskt-lists-published-${StageName}
      CodeUri: target/test-0.0.1-SNAPSHOT.jar
      Handler: com.gobaskt.offers.handlers.TaskRequestHandler::listOffers
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: TasksTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /gobaskt/offers/published
            Method: GET
            RestApiId:
              Ref: RestApi
  CreateLocaloffersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: gobaskt-create-localoffers-${StageName}
      CodeUri: target/test-0.0.1-SNAPSHOT.jar
      Handler: com.gobaskt.offers.handlers.TaskRequestHandler::createTask
      Policies:
        DynamoDBCrudPolicy:
          TableName:
            Ref: TasksTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /gobaskt/offers
            Method: POST
            RestApiId:
              Ref: RestApi
  GetLocaloffersBYIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: gobaskt-get-localoffersById-${StageName}
      CodeUri: target/test-0.0.1-SNAPSHOT.jar
      Handler: com.gobaskt.offers.handlers.TaskRequestHandler::getTask
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: TasksTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /gobaskt/offersById/{id}
            Method: GET
            RestApiId:
              Ref: RestApi
  GetLocaloffersBYIdsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: gobaskt-get-localoffersByIds-${StageName}
      CodeUri: target/test-0.0.1-SNAPSHOT.jar
      Handler: com.gobaskt.offers.handlers.TaskRequestHandler::getTaskByIDs
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: TasksTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /gobaskt/offersByIds/{id}
            Method: GET
            RestApiId:
              Ref: RestApi
  GetLocaloffersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: gobaskt-get-localoffers-${StageName}
      CodeUri: target/test-0.0.1-SNAPSHOT.jar
      Handler: com.gobaskt.offers.handlers.TaskRequestHandler::getProduct
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: TasksTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /gobaskt/offers/{search}
            Method: GET
            RestApiId:
              Ref: RestApi
  UpdateOffersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: gobaskt-update-offers-${StageName}
      CodeUri: target/test-0.0.1-SNAPSHOT.jar
      Handler: com.gobaskt.offers.handlers.TaskRequestHandler::updateTask
      Policies:
        DynamoDBCrudPolicy:
          TableName:
            Ref: TasksTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /gobaskt/offers/update/{id}
            Method: PUT
            RestApiId:
              Ref: RestApi
  ImageUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: gobaskt-update-image-${StageName}
      CodeUri: target/test-0.0.1-SNAPSHOT.jar
      Handler: com.gobaskt.offers.handlers.TaskRequestHandler::imageUpload
      Policies:
        DynamoDBCrudPolicy:
          TableName:
            Ref: TasksTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /gobaskt/offers/image
            Method: POST
            RestApiId:
              Ref: RestApi
  UpdateMultiOffersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: gobaskt-update-Multioffers-${StageName}
      CodeUri: target/test-0.0.1-SNAPSHOT.jar
      Handler: com.gobaskt.offers.handlers.TaskRequestHandler::updateTasks
      Policies:
        DynamoDBCrudPolicy:
          TableName:
            Ref: TasksTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /gobaskt/offers/updates/
            Method: PUT
            RestApiId:
              Ref: RestApi
  TasksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Fn::Sub: local
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1